### ISSUE TITLE
Misplaced article - PHP Category - 7 Mobile UX Mistakes

### ISSUE THREAD

**Issue by jeffreylees** [sitepoint-editors/sitepoint-bugs#1]
http://www.sitepoint.com/7-mobile-ux-mistakes/

Seems to not belong in PHP. Assuming "UX" or "Mobile Design"

**Comment by jeffreylees** [comment]
Actually, a decent chunk of the "Patterns and Practices" category seems to be misplaced, to me, unless it was intentional. Some of them seem appropriate, but there's several that seem to be entirely focused on UX...

**Comment by pageaffairs** [comment]
It's in Design & UX now.

**Comment by jeffreylees** [comment]
It's also still in PHP/Patterns&Practices though... is that intended?

**Comment by Swader** [comment]
Definitely not. Thanks for reporting, will get looked into. Possibly bigger in scale than few instances, and warrants further investigation. Possible that a cause, once removed, will solve all other cases.

**Comment by Swader** [comment]
It seems several Patters and Practices posts have been miscategorized. Whoever put them into categories didn't see that P&P belongs to the PHP superset. I have removed two offenders, but please let me know if there are more. Thanks!
