### ISSUE TITLE
SitePoint Premium 'forgot password' email confirmation still has old Learnable logo

### ISSUE THREAD

**Issue by elioqoshi** [sitepoint-editors/sitepoint-bugs#10]
We should update this
![learnable](https://cloud.githubusercontent.com/assets/5436686/10558394/2d7bc2a2-74cd-11e5-975d-671a7b88567a.jpg)

**Comment by Swader** [comment]
Ping @OphelieL

**Comment by elioqoshi** [comment]
@OphelieL is in vacations until 1st November or so

**Comment by AdamRobertsNZ** [comment]
I'm on this btw
