### ISSUE TITLE
Guide to Homestead Improved VM makes references to old version

### ISSUE THREAD

**Issue by AndrewCarterUK** [sitepoint-editors/sitepoint-bugs#15]
http://www.sitepoint.com/quick-tip-get-homestead-vagrant-vm-running/

As the vagrant environment was forked from Laravel Homestead, it originally retained the 'Laravel' folder name.

This became confusing, because there is no requirement to use Laravel, so it was switched to 'Project' instead.

However, there are a few references still left to 'Laravel' in the guide. A Ctrl-F should locate them, but I can count two - one in the article body and one in a code example.

**Comment by AndrewCarterUK** [comment]
Follow up, this article should also be changed:

http://www.sitepoint.com/ocr-in-php-read-text-from-images-with-tesseract/

As it references the old version of Homestead Improved too.

**Comment by Swader** [comment]
Fixed, thanks
