### ISSUE TITLE
Peer Reviews Introduction doesn't list all available channels

### ISSUE THREAD

**Issue by JeremyHeleine** [sitepoint-editors/sitepoint-bugs#16]
The page [Introduction to SitePoint’s Peer Review](http://www.sitepoint.com/introduction-to-sitepoints-peer-review/) lists PHP, Mobile and JavaScript as channels where peer reviews are implemented. However, there is at least one more channel to add to the list (WordPress). I think this page should be up to date and list all the channels using peer reviews.

**Comment by AdamRobertsNZ** [comment]
Excellent point Jeremy - fixed!
