### ISSUE TITLE
About Us - Team not complete

### ISSUE THREAD

**Issue by elioqoshi** [sitepoint-editors/sitepoint-bugs#17]
Would it be possible to add Chris Ward and yours truly to the team here?
http://www.sitepoint.com/about-us/

@OphelieL told me there were still some missing, but would be good to wrap this up :)

**Comment by elioqoshi** [comment]
Also apart @ChrisChinchilla , @impressivewebs @jameshibbard too (if I haven't forgotten anyone)

**Comment by ChrisChinchilla** [comment]
Don't see Angela either…

**Comment by elioqoshi** [comment]
@ChrisChinchilla did you forget your glasses? :stuck_out_tongue:

**Comment by ChrisChinchilla** [comment]
Oh, ignore me…

**Comment by elioqoshi** [comment]
also @chrisburgess
