### ISSUE TITLE
(Possible) Extremely minor bug with responsive nav menu?

### ISSUE THREAD

**Issue by jeffreylees** [sitepoint-editors/sitepoint-bugs#2]
If you shrink your browser window so that you get the hamburger, choose "Topics", and then expand your browser again, the hamburger-Topics menu becomes a nav bar across the top in black, while the normal topics-nav bar returns below it, and you have a double nav bar with no way that I see to dismiss the top one (the hamburger originated one) without a refresh or without shrinking, dismissing from hamburger menu, then resizing.

That's a pretty tiny reproduction scenario though, and anyone doing that is likely not a normal user or in a normal use case, so you might just want to ignore this. :)

Just FYI.

**Comment by OphelieL** [comment]
Thanks @jeffreylees! Pretty minor indeed but we'll fix it next time we're updating the nav.
