### ISSUE TITLE
Nav bar blank

### ISSUE THREAD

**Issue by davemaxwell77** [sitepoint-editors/sitepoint-bugs#3]
I'm not sure what I'm doing, but I'm seeing an empty nav bar quite often....here's a screen shot, but I've seen it over multiple categories (Design & UX was the first, and when I hit that one, all the categories were blank for a while...)

![image](https://cloud.githubusercontent.com/assets/12445398/7882991/ea765a5e-05e0-11e5-9c7c-350d9c694927.png)

**Comment by Swader** [comment]
Interesting. If you inspect the blank area with dev tools, do you get the elements, or are they actually missing? The reason I ask is that maybe it's a font issue that hangs.

**Comment by jameshibbard** [comment]
I'm getting the same thing when previewing articles I'm editing.

**Comment by jeffreylees** [comment]
I get that too but only momentarily. If I move about the nav bar, the dropdown populates.

**Comment by davemaxwell77** [comment]
When you mouse down into the box, the text appears, so it might be a hanging font issue.

I did find the ads are interfering as well.  First is the whole ad.  Second is just the adchoices triangle.
![image](https://cloud.githubusercontent.com/assets/12445398/7883215/cf4990aa-05e2-11e5-81dd-6ae66278687b.png)

![image](https://cloud.githubusercontent.com/assets/12445398/7883246/0ac2130a-05e3-11e5-938a-0293b5e436db.png)

**Comment by Swader** [comment]
Oof, not good. Thanks. subbing @OphelieL @AdamRobertsNZ

**Comment by TomTrumble** [comment]
Ping @ericawass

**Comment by OphelieL** [comment]
Launch bugs for the new nav, all fixed now!
