### ISSUE TITLE
From TechnoBear

### ISSUE THREAD

**Issue by davemaxwell77** [sitepoint-editors/sitepoint-bugs#5]
![image](https://cloud.githubusercontent.com/assets/12445398/7886176/435e0e40-05f6-11e5-9bda-3eed2608e8f0.png)

The navigation doesn't play nicely with text-only zoom on Firefox.  This image is from my PC, but there's a similar issue on my laptop.

(Note:  She doesn't have a github account so I'm reporting for her.  You can contact her directly via slack or SPF if you want more information)

**Comment by davemaxwell77** [comment]
Other issues from TB:

Broken header on homepage at text-zoom 110%:
![image](https://cloud.githubusercontent.com/assets/12445398/7886459/3a445cea-05f8-11e5-8797-7b40319e7b4f.png)

Broken navigation at text-zoom 110%:
![image](https://cloud.githubusercontent.com/assets/12445398/7886479/5086a508-05f8-11e5-99ce-0e5ffeb10567.png)

Other issues at 110% text zoom:
![image](https://cloud.githubusercontent.com/assets/12445398/7886489/631a0f98-05f8-11e5-91ed-267a09c57115.png)

![image](https://cloud.githubusercontent.com/assets/12445398/7886491/6b0db47a-05f8-11e5-8b31-a506ed36dc46.png)

(Those images are all from my desktop at 110% zoom. It's worse on my laptop, which has an HD screen and I need to zoom more than 110%.)

Thanks, guys.

Lesley

**Comment by TomTrumble** [comment]
Another one for you, @ericawass.

And thanks so much for letting us know, we've got a few good old teething issues with the new nav :)

**Comment by guido2004** [comment]
I believe TB doesn't run Windows, but I'm getting the same thing in FF38.0.5 under W7, and I didn't zoom (afaik):
![spmenu](https://cloud.githubusercontent.com/assets/12747352/7984224/d973f694-0ac7-11e5-8912-f6394de17c08.png)
