### ISSUE TITLE
Article 404

### ISSUE THREAD

**Issue by jeffreylees** [sitepoint-editors/sitepoint-bugs#6]
http://www.sitepoint.com/radar-titles-tables-robots/

**Comment by Swader** [comment]
How did you get to it? You can get a 404 by typing [literally anything](http://www.sitepoint.com/this-is-an-invalid-post-trololol) into the address bar, so it's more a matter of finding the resources that link TO this, not this itself :)

**Comment by jeffreylees** [comment]
Front page... Latest articles. The one about the contest.

**Comment by Swader** [comment]
Yikes. Thanks.
sub @OphelieL @AdamRobertsNZ @jasmineelias

**Comment by pageaffairs** [comment]
Wow, that's terrible. All the right buttons seem to have been pushed behind the scenes. :-/

**Comment by OphelieL** [comment]
Thanks for the heads-up @swader and @jeffreylees. I think I know what happened, I'll fix it when I'm back at a real computer.

**Comment by Swader** [comment]
Fixed by changing link to [this](http://www.sitepoint.com/radar-june-competition-titles-tables-robots/).
