### ISSUE TITLE
Z-index overlay issue

### ISSUE THREAD

**Issue by RyanReese09** [sitepoint-editors/sitepoint-bugs#7]
http://www.sitepoint.com/?s=bacon&type=post

Just an example URL (any results page works). Please hover over the categories. Like HTML,CSS, Ruby, etc. It is going behind the results. ".Channel .chan-nav" getting a z-index:12 fixes the issue (or anything over 11). It's currently 5. You should check whether this breaks anything though. Or find your own fix. Dunno.

Original issue found by "Younes Rafie" in Slack. Once I replicated, I found the fix.

**Comment by TomTrumble** [comment]
Thanks @RyanReese09, I've passed on your comments and this is now in the development backlog :)

**Comment by RyanReese09** [comment]
Thanks!
